# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(805, 664)
        Form.setStyleSheet("")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setStyleSheet("background-color: rgb(235, 248, 252);\n"
"border-radius:15px")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget = QtWidgets.QWidget(parent=self.widget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border:none;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(29)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.page)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(60)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 170, 127);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setAutoExclusive(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setAutoExclusive(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setAutoExclusive(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(200)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(95, 191, 141);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(73, 147, 109);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(152, 152, 152);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(131, 131, 131);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(18, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(29)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(parent=self.page_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(90)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(85, 170, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.page_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_8.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.page_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_7.setCursorPosition(0)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_8.addWidget(self.lineEdit_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, 0, 5)
        self.horizontalLayout_13.setSpacing(180)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.page_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(95, 191, 141);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(73, 147, 109);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_13.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.page_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(152, 152, 152);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(131, 131, 131);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_13.addWidget(self.pushButton_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        spacerItem8 = QtWidgets.QSpacerItem(17, 95, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(18, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(29)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.page_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(60)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 170, 127);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_4.setCursorPosition(0)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_5.setCursorPosition(0)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(200)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(152, 152, 152);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(131, 131, 131);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_11.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(95, 191, 141);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(73, 147, 109);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem12 = QtWidgets.QSpacerItem(17, 95, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem13 = QtWidgets.QSpacerItem(18, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(29)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(parent=self.page_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(90)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(85, 170, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(parent=self.page_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_10.addWidget(self.comboBox)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.page_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_10.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.page_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("border-radius:15px;\n"
"padding:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_9.setCursorPosition(0)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_10.addWidget(self.lineEdit_9)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, 0, 5)
        self.horizontalLayout_16.setSpacing(180)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.page_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(95, 191, 141);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(73, 147, 109);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_16.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.page_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(152, 152, 152);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(131, 131, 131);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_16.addWidget(self.pushButton_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        spacerItem16 = QtWidgets.QSpacerItem(17, 95, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem16)
        self.horizontalLayout_17.addLayout(self.verticalLayout_9)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7.addWidget(self.widget)
        self.horizontalLayout_10.addWidget(self.widget_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(3)
        self.pushButton.clicked.connect(Form.login) # type: ignore
        self.pushButton_2.clicked.connect(Form.open_register_page) # type: ignore
        self.pushButton_4.clicked.connect(Form.open_login_page) # type: ignore
        self.pushButton_5.clicked.connect(Form.register) # type: ignore
        self.pushButton_3.clicked.connect(Form.close) # type: ignore
        self.pushButton_6.clicked.connect(Form.close) # type: ignore
        self.lineEdit_7.returnPressed.connect(Form.add_school) # type: ignore
        self.lineEdit_5.returnPressed.connect(Form.register) # type: ignore
        self.lineEdit_2.returnPressed.connect(Form.login) # type: ignore
        self.pushButton_7.clicked.connect(Form.add_school) # type: ignore
        self.pushButton_8.clicked.connect(Form.add_course) # type: ignore
        self.pushButton_9.clicked.connect(Form.close) # type: ignore
        self.lineEdit_9.returnPressed.connect(Form.add_course) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "教务管理系统"))
        self.pushButton_3.setText(_translate("Form", "X"))
        self.label.setText(_translate("Form", "教务管理系统"))
        self.lineEdit.setPlaceholderText(_translate("Form", "账号"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "密码"))
        self.checkBox.setText(_translate("Form", "学生登录"))
        self.checkBox_2.setText(_translate("Form", "老师登录"))
        self.checkBox_3.setText(_translate("Form", "管理员登录"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.pushButton_2.setText(_translate("Form", "注册"))
        self.label_3.setText(_translate("Form", "创建学校"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "机构名称"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "机构地址"))
        self.pushButton_7.setText(_translate("Form", "注册"))
        self.pushButton_6.setText(_translate("Form", "关闭"))
        self.label_2.setText(_translate("Form", "管理员注册"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "账号"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "密码"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "确认密码"))
        self.pushButton_4.setText(_translate("Form", "登录"))
        self.pushButton_5.setText(_translate("Form", "注册"))
        self.label_4.setText(_translate("Form", "创建课程"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "课程名称"))
        self.lineEdit_9.setPlaceholderText(_translate("Form", "课程价格"))
        self.pushButton_8.setText(_translate("Form", "注册"))
        self.pushButton_9.setText(_translate("Form", "关闭"))
